name: build-release

on: push

env:
  IMAGE_NAME: plantuml-server-native

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew bootJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            src/main/docker
            build/libs
  docker:
    if: startsWith( github.ref, 'refs/tags/')
    name: Push docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Display structure of downloaded files
        run: ls -R

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker buildx build \
            --tag nxest/$IMAGE_NAME:$VERSION \
            --tag nxest/$IMAGE_NAME:lastest \
            --platform linux/amd64,linux/arm64 \
            -f src/main/docker/Dockerfile ./ \
            --push
